INSERT INTO WORKERS(WORKER_NAME, SALARIO_DIA) VALUES ('Thiago', 3200.0);
INSERT INTO WORKERS(WORKER_NAME, SALARIO_DIA) VALUES ('Vania', 2200.0);
INSERT INTO WORKERS(WORKER_NAME, SALARIO_DIA) VALUES ('Gica', 2800.0);
INSERT INTO WORKERS(WORKER_NAME, SALARIO_DIA) VALUES ('Mimi', 1200.0);